language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

cache:
  directories:
    - vendor

matrix:
  fast_finish: true
  allow_failures:
    - php: '5.4'
    - php: '5.5'
    - php: nightly

install:
  - composer install

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --testdox || vendor/bin/phpunit --verbose
